server.host: "0.0.0.0"
server.port: 5601
elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.username: "elastic"
elasticsearch.password: "changeme"
elasticsearch.ssl.certificateAuthorities: ["/usr/share/elasticsearch/config/certs/http_ca.crt"]
elasticsearch.ssl.verificationMode: full